import { test } from 'node:test';
import assert from 'node:assert/strict';
import { MultiPassCompiler } from '../src/compiler/index.mjs';
import { GccAdapter, parseGccJson } from '../src/compiler/adapters/gcc.mjs';
import { V8Adapter, summarizeBytecode } from '../src/compiler/adapters/v8.mjs';
import { LlvmAdapter } from '../src/compiler/adapters/llvm.mjs';
import { GraalVmAdapter } from '../src/compiler/adapters/graalvm.mjs';
import { Severity } from '../src/compiler/feedback.mjs';

test('adapter registry exposes all four reference adapters', () => {
  const compiler = MultiPassCompiler.standard();
  const names = compiler.list().map((c) => c.name).sort();
  assert.deepEqual(names, ['gcc', 'graalvm', 'llvm', 'v8']);
});

test('pipeline planning selects adapters by language', () => {
  const compiler = MultiPassCompiler.standard();
  assert.deepEqual(compiler.plan('c').sort(), ['gcc', 'llvm']);
  assert.deepEqual(compiler.plan('ecmascript').sort(), ['graalvm', 'v8']);
  assert.deepEqual(compiler.plan('java'), ['graalvm']);
});

test('unknown language yields a clear error', () => {
  const compiler = MultiPassCompiler.standard();
  assert.throws(() => compiler.compile({ language: 'cobol', source: 'x' }), /no adapter supports/);
});

test('feedback document is normalised across passes', () => {
  const compiler = new MultiPassCompiler([new LlvmAdapter(), new GraalVmAdapter()]);
  const report = compiler.compile({
    name: 'u',
    language: 'rust',
    source: 'fn main() { let unused = 1; for _ in 0..10 {} }',
    adapters: ['llvm', 'graalvm'],
  });
  assert.equal(report.unit.name, 'u');
  assert.deepEqual(report.pipeline, ['llvm', 'graalvm']);
  assert.equal(typeof report.summary.errors, 'number');
  assert.equal(typeof report.summary.warnings, 'number');
  assert.ok(report.remarks.length > 0);
  // Remarks are deduplicated across passes.
  const keys = report.remarks.map((r) => `${r.pass}|${r.message}`);
  assert.equal(new Set(keys).size, keys.length);
});

test('llvm adapter emits a deterministic .ll artifact', () => {
  const adapter = new LlvmAdapter();
  const fb = adapter.run('u', 'c', 'int f(){return 1;}');
  const artifact = fb.artifacts.find((a) => a.kind === 'llvm-ir');
  assert.ok(artifact);
  const text = new TextDecoder().decode(artifact.bytes);
  assert.match(text, /ModuleID = 'u'/);
  assert.match(text, /target triple/);
});

test('graalvm adapter reports availability and models when absent', () => {
  const adapter = new GraalVmAdapter();
  const caps = adapter.capabilities();
  assert.equal(caps.name, 'graalvm');
  assert.ok(caps.languages.includes('java'));
  const fb = adapter.run('u', 'java', 'class A { void f() {} }');
  assert.equal(fb.adapter, 'graalvm');
  assert.ok(fb.artifacts.some((a) => a.kind === 'graal-feedback'));
});

test('gcc json parser handles concatenated objects', () => {
  const json = [
    '{"kind":"error","message":"boom","locations":[{"caret":{"file":"a.c","line":3,"column":7}}]}',
    '{"kind":"warning","message":"meh","locations":[{"caret":{"file":"a.c","line":4,"column":1}}]}',
  ].join('\n');
  const diagnostics = parseGccJson(json);
  assert.equal(diagnostics.length, 2);
  assert.equal(diagnostics[0].severity, Severity.ERROR);
  assert.equal(diagnostics[0].line, 3);
  assert.equal(diagnostics[1].severity, Severity.WARNING);
});

test('v8 bytecode summary counts functions and sizes', () => {
  const summary = summarizeBytecode(
    '[generated bytecode for function:  (0x1)]\nBytecode length: 5\nHandler Table (size = 1)\n',
  );
  assert.equal(summary.functions, 1);
  assert.equal(summary.bytecodeLength, 5);
  assert.equal(summary.withTryCatch, 1);
});

test('gcc adapter measures real diagnostics when gcc is present', { skip: !new GccAdapter().available }, () => {
  const adapter = new GccAdapter();
  const fb = adapter.run('bad', 'c', 'int main(void){ return missing_symbol; }');
  assert.equal(fb.ok, false);
  assert.ok(fb.diagnostics.some((d) => d.severity === Severity.ERROR));
});

test('v8 adapter produces real ignition bytecode', { skip: !new V8Adapter().available }, () => {
  const adapter = new V8Adapter();
  const fb = adapter.run('u', 'ecmascript', 'function f(a,b){return a+b;} f(1,2);');
  const artifact = fb.artifacts.find((a) => a.kind === 'v8-bytecode');
  assert.ok(artifact, 'expected v8 bytecode artifact');
  assert.ok(artifact.bytes.length > 0);
});
