import { CompilerAdapter, Diagnostic, Remark, Feedback, Severity } from '../feedback.mjs';
import { analyze } from './analyze.mjs';
import { nodeTools } from './node-tools.mjs';

/**
 * V8 adapter.
 *
 * Drives the host V8 through `node --print-bytecode` to capture real Ignition
 * bytecode for ECMAScript units, then derives feedback (bytecode size,
 * function count, deopt risk) from it. This is the adapter that makes b8g's
 * "v8 compatible snapshots" claim concrete: the feedback is V8's own.
 *
 * Outside Node (e.g. in the browser console) there is no child process to
 * drive, so the adapter degrades to modelled feedback from the static analyser.
 */
export class V8Adapter extends CompilerAdapter {
  constructor(opts = {}) {
    super('v8');
    this.timeoutMs = opts.timeoutMs ?? 10_000;
    this.tools = nodeTools();
    this.available = this._detect();
  }

  _detect() {
    if (!this.tools) return false;
    const probe = this.tools.spawnSync(this.tools.execPath, ['--version'], { encoding: 'utf8' });
    return probe.status === 0;
  }

  capabilities() {
    return {
      name: 'v8',
      languages: ['ecmascript', 'typescript', 'javascript'],
      passes: ['parser', 'ignition', 'sparkplug', 'maglev', 'turbofan'],
      backend: 'v8/ignition+turbofan',
      available: this.available,
      feedbackOnly: false,
    };
  }

  compile(unit) {
    const { facts, diagnostics, remarks } = analyze(unit.source, unit.language);
    const artifacts = [];
    const timings = { frontendMs: 0, optimizeMs: 0, codegenMs: 0 };

    if (this.available) {
      const dir = this.tools.mkdtempSync(this.tools.join(this.tools.tmpdir(), 'b8g-v8-'));
      const file = this.tools.join(dir, 'unit.mjs');
      const start = Date.now();
      try {
        this.tools.writeFileSync(file, unit.source);
        const res = this.tools.spawnSync(this.tools.execPath, ['--print-bytecode', file], {
          encoding: 'utf8',
          timeout: this.timeoutMs,
          maxBuffer: 16 * 1024 * 1024,
        });
        timings.frontendMs = Date.now() - start;
        const stderr = res.stderr || '';
        if (res.status !== 0) {
          diagnostics.push(
            new Diagnostic({
              severity: Severity.ERROR,
              message: firstErrorLine(stderr) ?? 'v8 failed to parse unit',
              pass: 'parser',
            }),
          );
        }
        const bytecode = res.stdout || '';
        const summary = summarizeBytecode(bytecode);
        if (summary.functions > 0) {
          artifacts.push({
            name: `${unit.name}.bytecode`,
            kind: 'v8-bytecode',
            bytes: new TextEncoder().encode(bytecode),
          });
          remarks.push(
            new Remark({
              pass: 'ignition',
              message: `${summary.functions} bytecode function(s), ${summary.bytecodeLength} bytes emitted`,
              impact: summary.bytecodeLength,
            }),
          );
        }
        if (summary.withTryCatch > 0) {
          diagnostics.push(
            new Diagnostic({
              severity: Severity.NOTE,
              message: `${summary.withTryCatch} handler table(s) — try/catch prevents some inlining`,
              pass: 'turbofan',
            }),
          );
        }
        void facts;
      } finally {
        this.tools.rmSync(dir, { recursive: true, force: true });
      }
    }

    return new Feedback('v8', unit, { diagnostics, remarks, artifacts, timings });
  }
}

export function summarizeBytecode(text) {
  const functions = (text.match(/\[generated bytecode for function:/g) || []).length;
  const lengths = [...text.matchAll(/Bytecode length:\s*(\d+)/g)].map((m) => Number(m[1]));
  const withTryCatch = (text.match(/Handler Table \(size = [1-9]/g) || []).length;
  return {
    functions,
    bytecodeLength: lengths.reduce((a, b) => a + b, 0),
    withTryCatch,
  };
}

function firstErrorLine(stderr) {
  const line = stderr.split(/\r?\n/).find((l) => l.trim().length);
  return line ? line.trim() : null;
}
